<?php

namespace AppBundle\Repository;

/**
 * Call_offerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Call_offerRepository extends \Doctrine\ORM\EntityRepository
{
}
