<?php

namespace AppBundle\Repository;

/**
 * EtrepriseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EtrepriseRepository extends \Doctrine\ORM\EntityRepository
{
}
