<?php

namespace AppBundle\Repository;

/**
 * Expression_interestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExpressionOfinterestRepository extends \Doctrine\ORM\EntityRepository
{
}
