<?php

namespace AppBundle\Repository;

/**
 * HistoricalAlertSubscriberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoricalAlertSubscriberRepository extends \Doctrine\ORM\EntityRepository
{
}
