<?php

namespace AppBundle\Repository;

/**
 * HistoricalAlertEntrepriseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HistoricalAlertEntrepriseRepository extends \Doctrine\ORM\EntityRepository
{
}
