<?php

namespace AppBundle\Repository;

/**
 * SpecialFollowUpRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SpecialFollowUpRepository extends \Doctrine\ORM\EntityRepository
{
}
