<?php

namespace AppBundle\Repository;

/**
 * SubcriptionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SubcriptionRepository extends \Doctrine\ORM\EntityRepository
{
}
